### PR TITLE
Storyline and selections

### PR DESCRIPTION
**Pull request by theq629**
For #168, #183, and #186.

Someone else should play with it (all the views but especially storyline and facet) in case I introduced new bugs, but it's basically ready. It's running on my demo site.

### CODE REVIEW

**Comment by vlad003** [comment]
What's your demo site?

**Comment by theq629** [comment]
http://lensingwikipedia.cs.sfu.ca:9000/

**Comment by anoopsarkar** [comment]
The demo site has crashed?

**Comment by theq629** [comment]
Yes, it seems to be down. I don't know why.

**Pull request merged**
