### PR TITLE
Use Flask to serve Lensing instead of statically serve index.html

### PR DESCRIPTION
**Pull request by vlad003**
This allows us to work on the same code (instead of me copying code from `frontend/` to test).

All of the javascript and CSS served by this is a direct copy of what's in `frontend/`, so nothing changed in terms of functionality. The domain specific .js files are controlled by a `config.py` and conditionals within the templates.

So far I've only tested the wikipediahistory domain (the default) since I'm not too sure what avherald should look like. I wrote all of the `<script>` and `<link>` tags based on the Makefiles, so it _should_ work the same as before.

### CODE REVIEW

**Comment by anoopsarkar** [comment]
Can I serve on port 80 when master is deployed to natlang-web.cs.sfu.ca?

Is there a howto in website.md with step by step instructions?

**Comment by vlad003** [comment]
It should work fine with mod_wsgi. I'll test it tomorrow (or later today, rather) and I'll update website.md with details.

**Comment by vlad003** [comment]
I added some more details to website.md about how to set up mod_wsgi. I just set it up on CentOS 6.6 with the configs in website.md, and it seems to work. It's set up at http://104.131.157.126/ (which I'll take down in a few days) without the query backend and I can give you access to that server to see how it's set up (if website.md doesn't make sense).

**Comment by anoopsarkar** [comment]
Thanks, it looks good. What about the lensing-backend.conf for upstart. I assume that needs changing too?

**Comment by vlad003** [comment]
No, that's completely separate.

**Comment by anoopsarkar** [comment]
d'oh. you're right. upstart is used to launch the backend and has nothing to do with serving the frontend.

ok. I will merge and update the webserver with master.

**Pull request merged**
