### PR TITLE
theq629's backend makefile proposal

### PR DESCRIPTION
**Pull request by theq629**
I would like to merge my proposal for #176. If it doesn't work for @KonceptGeek as is, it is easy to add specific makefile variables as I describe in that issue.

### CODE REVIEW

**Comment by vlad003** [comment]
Did merging master into your branch not overwrite some of your changes?

**Comment by theq629** [comment]
I'm pretty sure all the changes did get in, I redid it after the backend reorganization in #181.

The changes should be:
- local makefile (already in master from #181)
- no hardcoded library paths
- bhtsne has its own makefile
- bhtsne source files aren't copied to output

**Comment by vlad003** [comment]
I've met with @anoopsarkar today and we decided that I'll merge this branch into my 'dockerize' branch, and then when I finish up testing that branch, I'll create a PR against master.

**Comment by theq629** [comment]
Ok, sounds good.

**Pull request closed without merging**
