### PR TITLE
Smoothed timeline

### PR DESCRIPTION
**Pull request by vlad003**
If the cluster view conflicts with this, I'll fix it and update this pull request after that's merged.

### CODE REVIEW

**Comment by anoopsarkar** [comment]
should we merge this pull request before the tSNE merge? Jasneet?

**Comment by KonceptGeek** [comment]
Yeah we can merge it as I haven't touched timeline.js. Also the tSNE branch is almost ready to be merged. I've already merged master into tSNE branch to resolve conflicts and I'm just testing if everything is working and updating the website.md.

**Comment by anoopsarkar** [comment]
Andrei: did you merge with current master after story line merge? also: any changes to backend?

**Comment by vlad003** [comment]
Yeah, I merged master a few hours ago. And no, there's no changes to the backend.

**Comment by anoopsarkar** [comment]
ok. let's merge timeline before tSNE. 

and Happy New Year!

**Pull request merged**
